name: GitHub Actions - Push - Branch Ignore Template
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:

jobs:
  on-workflow_dispatch:

    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário workflow dispatch"
